name: Release
on:
  push:
    branches:
    - main

permissions:
  contents: write 

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: main